@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class PoliticalAgent {
  name
  email
}

class Declaration {
  submissionDate
}

class Position {
  remuneration
}

class Subsidy {
  amount
}

PoliticalAgent "1" -- "0..*" Declaration : submits >
Declaration "1" -- "0..*" Position : contains >
Declaration "1" -- "0..*" Subsidy : contains >

@enduml