@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ConsultIntegratedSituationController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "declarationRepository:\nDeclarationRepository" as DECL_REPO
participant "member\n:EthicsCommitteeMember" as MEMBER
participant "integratedSituation\n:IntegratedSituation" as INTEGRATED_SITUATION
participant "IntegratedSituationMapper" as INTEG_MAPPER

autonumber 8
-> CTRL : consultIntegratedSituation(politicalAgentDTO, referenceDate)

autonumber 8.1
activate CTRL
    group Build Integrated Situation

        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL : repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON : getDeclarationRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL : declarationRepository
        deactivate REPOS_SINGLETON

        CTRL -> DECL_REPO : getDeclarationsByPoliticalAgentUntilDate(politicalAgentDTO.agentId, referenceDate)
        activate DECL_REPO
            DECL_REPO --> CTRL : declarations
        deactivate DECL_REPO

        CTRL -> MEMBER : buildIntegratedSituation(politicalAgentDTO.agentId, declarations, referenceDate)
        activate MEMBER
            MEMBER --> INTEGRATED_SITUATION** : create(agentId, referenceDate)
            MEMBER -> INTEGRATED_SITUATION : aggregateFromDeclarations(declarations)
            activate INTEGRATED_SITUATION
                INTEGRATED_SITUATION --> MEMBER : integratedSituation
            deactivate INTEGRATED_SITUATION

            MEMBER --> CTRL : integratedSituation
        deactivate MEMBER

        CTRL -> INTEG_MAPPER : toDTO(integratedSituation)
        activate INTEG_MAPPER
            INTEG_MAPPER --> CTRL : integratedSituationDTO
        deactivate INTEG_MAPPER

    end
    autonumber 9
    <-- CTRL : integratedSituationDTO
deactivate CTRL

@enduml
