@startuml
title US08 - Validate Declaration
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

skinparam class {
    BackgroundColor<<Abstract>> White
    BackgroundColor<<Enum>> White
}

enum DeclarationStatus << Enum >> {
  SUBMITTED
  VALIDATED
  REJECTED
}

enum ValidationVerdict << Enum >> {
  APPROVED
  REJECTED
}

class EthicsCommitteeMember {
}

class Declaration {
    submissionDate
}

class Validation {
    validationDate
}

class Annotation {
    text
    creationDate
}

class Subsidy {
    amount
    nature
}

class Asset {
    acquisitionValue
    marketValue
}

class Position {
    startDate
    endDate
    remuneration
}

class SecurityHolding {
    title
    marketValue
    stake
    percentage
}

EthicsCommitteeMember "1" -- "0..*" Validation : performs >
Validation "1" -- "1" Declaration : evaluates >
Validation --> "1" ValidationVerdict
Declaration --> "1" DeclarationStatus
Validation "1" *-- "0..*" Annotation : contains >
Annotation "0..*" -- "0..1" Subsidy : comments on >
Annotation "0..*" -- "0..1" Asset : comments on >
Annotation "0..*" -- "0..1" Position : comments on >
Annotation "0..*" -- "0..1" SecurityHolding : comments on >

@enduml