@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class EthicsCommitteeMember {
    name
    email
    password
}

class DeclarationOfInterests {
    submissionDate
    status
}

class Section {
    designation
}

class Comment {
    text
    date
}

EthicsCommitteeMember "1" -- "0..*" DeclarationOfInterests : validates >
DeclarationOfInterests "1" -- "1..*" Section : contains >
Section "0..1" -- "0..*" Comment : has >
EthicsCommitteeMember "1" -- "0..*" Comment : writes >

@enduml