@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ValidateDeclarationController" as CTRL
participant "member\n:EthicsCommitteeMember" as MEMBER
participant "declaration\n:Declaration" as DECL
participant "validation\n:Validation" as VALIDATION
participant "annotation\n:Annotation" as ANNOTATION

autonumber 15
-> CTRL : rejectDeclaration(targetReference, commentText)

autonumber 15.1
activate CTRL

    group Reject Declaration

        note right of CTRL
            member was obtained through
            the Get Ethics Committee Member
            partial SD
        end note

        CTRL -> MEMBER : validateDeclaration(declaration, REJECTED, targetReference, commentText)
        activate MEMBER
            MEMBER --> VALIDATION** : create(declaration, REJECTED)

            VALIDATION -> VALIDATION : addAnnotation(commentText, targetReference, declaration)
            activate VALIDATION
                VALIDATION --> ANNOTATION** : create(commentText, targetReference, declaration)
                VALIDATION --> VALIDATION : annotation
            deactivate VALIDATION

            MEMBER -> DECL : reject()
            activate DECL
                DECL --> MEMBER : status updated
            deactivate DECL

            MEMBER -> MEMBER : addValidation(validation)
            activate MEMBER
                MEMBER --> MEMBER : true
            deactivate MEMBER

            MEMBER --> CTRL : validation
        deactivate MEMBER

    end

    autonumber 16
    <-- CTRL : validation

deactivate CTRL

@enduml
