@startuml
title US03 - List Institutions
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class PoliticalAgent {
}

class Institution {
    name
    taxId
}

enum InstitutionType << Enum >> {
  COMPANY
  POLITICAL_PARTY
  FOUNDATION
  INSTITUTE
  ASSOCIATION
}

PoliticalAgent "1" -- "0..*" Institution : consults >
Institution --> "1" InstitutionType

@enduml