@startuml US006-SD-partial-get-political-agent
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":SubmitDeclarationController" as CTRL
participant "ApplicationSession" as APP_SESSION
participant "appSession\n:ApplicationSession" as APP
participant "userSession\n:UserSession" as SESSION
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "politicalAgentRepository\n:PoliticalAgentRepository" as PA_REPO

autonumber 10
-> CTRL : getPoliticalAgentFromSession()

autonumber 10.1
activate CTRL

    group Get Political Agent

        CTRL -> APP_SESSION : getInstance()
        activate APP_SESSION
            APP_SESSION --> CTRL : appSession
        deactivate APP_SESSION

        CTRL -> APP : getCurrentSession()
        activate APP
            APP --> CTRL : userSession
        deactivate APP

        CTRL -> SESSION : getUserId()
        activate SESSION
            SESSION --> CTRL : userId
        deactivate SESSION

        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL : repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON : getPoliticalAgentRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL : politicalAgentRepository
        deactivate REPOS_SINGLETON

        CTRL -> PA_REPO : getByUserId(userId)
        activate PA_REPO
            PA_REPO --> CTRL : politicalAgent
        deactivate PA_REPO

    end

    autonumber 11
    <-- CTRL : politicalAgent

deactivate CTRL

@enduml