@startuml US006-SD-full
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Political Agent" as PA

participant ":SubmitDeclarationUI" as UI
participant ":SubmitDeclarationController" as CTRL
participant "ApplicationSession" as APP_SESSION
participant "appSession\n:ApplicationSession" as APP
participant "userSession\n:UserSession" as SESSION
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "politicalAgentRepository\n:PoliticalAgentRepository" as PA_REPO
participant "institutionRepository\n:InstitutionRepository" as INST_REPO
participant "functionRepository\n:FunctionRepository" as FUNC_REPO
participant "declarationRepository\n:DeclarationRepository" as DECL_REPO
participant "politicalAgent\n:PoliticalAgent" as PAO
participant "declaration\n:Declaration" as DECL

activate PA

    PA -> UI : asks to submit a declaration of interests
    activate UI
        UI --> CTRL** : create()

        UI -> CTRL : getDeclarationTypes()
        activate CTRL
            CTRL --> UI : declarationTypes
        deactivate CTRL

        UI -> CTRL : getInstitutions()
        activate CTRL
            CTRL -> REPOS : getInstance()
            activate REPOS
                REPOS --> CTRL : repositories
            deactivate REPOS

            CTRL -> REPOS_SINGLETON : getInstitutionRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL : institutionRepository
            deactivate REPOS_SINGLETON

            CTRL -> INST_REPO : getAllInstitutions()
            activate INST_REPO
                INST_REPO --> CTRL : institutions
            deactivate INST_REPO

            CTRL --> UI : institutionDTOList
        deactivate CTRL

        UI -> CTRL : getFunctions()
        activate CTRL
            CTRL -> REPOS : getInstance()
            activate REPOS
                REPOS --> CTRL : repositories
            deactivate REPOS

            CTRL -> REPOS_SINGLETON : getFunctionRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL : functionRepository
            deactivate REPOS_SINGLETON

            CTRL -> FUNC_REPO : getAllFunctions()
            activate FUNC_REPO
                FUNC_REPO --> CTRL : functions
            deactivate FUNC_REPO

            CTRL --> UI : functionDTOList
        deactivate CTRL

        UI --> PA : requests declaration data
    deactivate UI

    PA -> UI : provides declaration data
    activate UI
        UI --> PA : shows entered data and requests confirmation
    deactivate UI

    PA -> UI : confirms declaration submission
    activate UI
        UI -> CTRL : submitDeclaration(declarationDTO)
        activate CTRL

            CTRL -> APP_SESSION : getInstance()
            activate APP_SESSION
                APP_SESSION --> CTRL : appSession
            deactivate APP_SESSION

            CTRL -> APP : getCurrentSession()
            activate APP
                APP --> CTRL : userSession
            deactivate APP

            CTRL -> SESSION : getUserId()
            activate SESSION
                SESSION --> CTRL : userId
            deactivate SESSION

            CTRL -> REPOS : getInstance()
            activate REPOS
                REPOS --> CTRL : repositories
            deactivate REPOS

            CTRL -> REPOS_SINGLETON : getPoliticalAgentRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL : politicalAgentRepository
            deactivate REPOS_SINGLETON

            CTRL -> PA_REPO : getByUserId(userId)
            activate PA_REPO
                PA_REPO --> CTRL : politicalAgent
            deactivate PA_REPO

            CTRL -> PAO : createDeclaration(declarationDTO.type)
            activate PAO
                PAO --> DECL** : create(declarationType, submissionDate)
                PAO --> CTRL : declaration
            deactivate PAO

            loop for each positionDTO
                CTRL -> INST_REPO : getById(positionDTO.institutionId)
                activate INST_REPO
                    INST_REPO --> CTRL : institution
                deactivate INST_REPO

                CTRL -> FUNC_REPO : getById(positionDTO.functionId)
                activate FUNC_REPO
                    FUNC_REPO --> CTRL : function
                deactivate FUNC_REPO

                CTRL -> DECL : addPosition(positionDTO.positionType, positionDTO.startDate,\npositionDTO.endDate, positionDTO.remuneration, function, institution)
                activate DECL
                    DECL --> CTRL : position
                deactivate DECL
            end

            loop for each subsidyDTO
                CTRL -> INST_REPO : getById(subsidyDTO.institutionId)
                activate INST_REPO
                    INST_REPO --> CTRL : institution
                deactivate INST_REPO

                CTRL -> DECL : addSubsidy(subsidyDTO.amount, subsidyDTO.nature, institution)
                activate DECL
                    DECL --> CTRL : subsidy
                deactivate DECL
            end

            loop for each assetDTO
                CTRL -> DECL : addAsset(assetDTO.propertyType, assetDTO.acquisitionValue,\nassetDTO.marketValue, assetDTO.location.parish,\nassetDTO.location.county, assetDTO.location.district)
                activate DECL
                    DECL --> CTRL : asset
                deactivate DECL
            end

            loop for each securityHoldingDTO
                CTRL -> INST_REPO : getById(securityHoldingDTO.institutionId)
                activate INST_REPO
                    INST_REPO --> CTRL : institution
                deactivate INST_REPO

                CTRL -> DECL : addSecurityHolding(securityHoldingDTO.title, securityHoldingDTO.marketValue,\nsecurityHoldingDTO.stake, securityHoldingDTO.percentage, institution)
                activate DECL
                    DECL --> CTRL : securityHolding
                deactivate DECL
            end

            CTRL -> DECL : validateData()
            activate DECL
                DECL --> CTRL : true
            deactivate DECL

            CTRL -> REPOS_SINGLETON : getDeclarationRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL : declarationRepository
            deactivate REPOS_SINGLETON

            CTRL -> DECL_REPO : save(declaration)
            activate DECL_REPO
                DECL_REPO --> CTRL : declaration
            deactivate DECL_REPO

            CTRL --> UI : declaration
        deactivate CTRL

        UI --> PA : informs that the declaration was successfully submitted
    deactivate UI

deactivate PA

@enduml