@startuml US006-SD-partial-create-declaration
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":SubmitDeclarationController" as CTRL
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "institutionRepository\n:InstitutionRepository" as INST_REPO
participant "functionRepository\n:FunctionRepository" as FUNC_REPO
participant "declarationRepository\n:DeclarationRepository" as DECL_REPO
participant "politicalAgent\n:PoliticalAgent" as PAO
participant "declaration\n:Declaration" as DECL

autonumber 20
-> CTRL : createDeclaration(politicalAgent, declarationDTO)

autonumber 20.1
activate CTRL

    group Create Declaration

        CTRL -> REPOS_SINGLETON : getDeclarationRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL : declarationRepository
        deactivate REPOS_SINGLETON

        alt declarationDTO.type == INITIAL
            CTRL -> DECL_REPO : existsInitialDeclaration(politicalAgent)
            activate DECL_REPO
                DECL_REPO --> CTRL : false
            deactivate DECL_REPO
        else declarationDTO.type == REGULAR
            CTRL -> DECL_REPO : existsRegularDeclarationForYear(politicalAgent, year)
            activate DECL_REPO
                DECL_REPO --> CTRL : false
            deactivate DECL_REPO
        end

        CTRL -> PAO : createDeclaration(declarationDTO.type)
        activate PAO
            PAO --> DECL** : create(declarationType, submissionDate)
            PAO --> CTRL : declaration
        deactivate PAO

        loop for each householdMemberDTO
            CTRL -> DECL : addHouseholdMember(householdMemberDTO.name,\nhouseholdMemberDTO.taxId, householdMemberDTO.birthDate,\nhouseholdMemberDTO.relationship)
            activate DECL
                DECL --> CTRL : householdMember
            deactivate DECL
        end

        loop for each positionDTO
            CTRL -> INST_REPO : getById(positionDTO.institutionId)
            activate INST_REPO
                INST_REPO --> CTRL : institution
            deactivate INST_REPO

            CTRL -> FUNC_REPO : getById(positionDTO.functionId)
            activate FUNC_REPO
                FUNC_REPO --> CTRL : function
            deactivate FUNC_REPO

            CTRL -> DECL : addPosition(positionDTO.positionType, positionDTO.startDate,\npositionDTO.endDate, positionDTO.remuneration, function, institution)
            activate DECL
                DECL --> CTRL : position
            deactivate DECL
        end

        loop for each subsidyDTO
            CTRL -> INST_REPO : getById(subsidyDTO.institutionId)
            activate INST_REPO
                INST_REPO --> CTRL : institution
            deactivate INST_REPO

            CTRL -> DECL : addSubsidy(subsidyDTO.amount, subsidyDTO.nature, institution)
            activate DECL
                DECL --> CTRL : subsidy
            deactivate DECL
        end

        loop for each assetDTO
            CTRL -> CTRL : mapToLocation(assetDTO.location)
            activate CTRL
                CTRL --> CTRL : location
            deactivate CTRL

            CTRL -> DECL : addAsset(assetDTO.propertyType, assetDTO.acquisitionValue,\nassetDTO.marketValue, location)
            activate DECL
                DECL --> CTRL : asset
            deactivate DECL
        end

        loop for each securityHoldingDTO
            CTRL -> INST_REPO : getById(securityHoldingDTO.institutionId)
            activate INST_REPO
                INST_REPO --> CTRL : institution
            deactivate INST_REPO

            CTRL -> DECL : addSecurityHolding(securityHoldingDTO.title, securityHoldingDTO.marketValue,\nsecurityHoldingDTO.stake, securityHoldingDTO.percentage, institution)
            activate DECL
                DECL --> CTRL : securityHolding
            deactivate DECL
        end

        alt declarationDTO.type == EXCEPTIONAL
            CTRL -> DECL : setAmendmentReason(declarationDTO.amendmentReason)
            activate DECL
            deactivate DECL

            opt declarationDTO.amendedDeclarationId != null
                CTRL -> DECL_REPO : getById(declarationDTO.amendedDeclarationId)
                activate DECL_REPO
                    DECL_REPO --> CTRL : amendedDeclaration
                deactivate DECL_REPO

                CTRL -> DECL : setAmendedDeclaration(amendedDeclaration)
                activate DECL
                deactivate DECL
            end
        end

        CTRL -> DECL : validateData()
        activate DECL
            DECL --> CTRL : true
        deactivate DECL

        CTRL -> DECL_REPO : save(declaration)
        activate DECL_REPO
            DECL_REPO --> CTRL : declaration
        deactivate DECL_REPO

    end

    autonumber 21
    <-- CTRL : declaration

deactivate CTRL

@enduml
