@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Ethics Committee\nMember" as Member
participant ":System" as System

activate Member

    Member -> System : asks to validate a declaration of interests
    activate System
        System --> Member : presents list of submitted declarations
    deactivate System

    Member -> System : selects a declaration of interests
    activate System
        System --> Member : shows declaration details
    deactivate System

    alt declaration is correct
        Member -> System : approves the declaration
        activate System
            System --> Member : informs that the declaration was successfully validated
        deactivate System
    else declaration has inconsistencies
        Member -> System : rejects the declaration with comments on inconsistent sections
        activate System
            System --> Member : informs that the declaration was rejected and returned for correction
        deactivate System
    end

deactivate Member
@enduml