@startuml
title US01 — User Registration Request
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

skinparam class {
    BackgroundColor<<Enum>> White
}

enum RequestedRole << Enum >> {
  POLITICAL_AGENT
  CITIZEN
  JOURNALIST
  ETHICS_COMMITTEE_MEMBER
}

enum RequestStatus << Enum >> {
  PENDING
  ACCEPTED
  REJECTED
}

class FutureUser {
}

class RegistrationRequest {
  requestDate
  name
  taxId
  email
  password
  nationalIdentityCardNumber
  pressCardNumber
  requestedPosition
  requestedInstitution
}

FutureUser "1" -- "0..*" RegistrationRequest : requests >
RegistrationRequest --> "1" RequestStatus
RegistrationRequest --> "1" RequestedRole

@enduml