@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":SubmitComplaintController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "politicalAgentRepository\n:PoliticalAgentRepository" as AGENT_REPO
participant "PoliticalAgentMapper" as AGENT_MAPPER
participant "roleRepository\n:RoleRepository" as ROLE_REPO
participant "RoleMapper" as ROLE_MAPPER

autonumber 3
-> CTRL : getPoliticalAgents()
autonumber 3.1
activate CTRL
    group Get Reference Data
        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL : repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON : getPoliticalAgentRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL : politicalAgentRepository
        deactivate REPOS_SINGLETON

        CTRL -> AGENT_REPO : getPoliticalAgents()
        activate AGENT_REPO
            AGENT_REPO --> CTRL : politicalAgentList
        deactivate AGENT_REPO

        CTRL -> AGENT_MAPPER : toDTOList(politicalAgentList)
        activate AGENT_MAPPER
            AGENT_MAPPER --> CTRL : politicalAgentDTOList
        deactivate AGENT_MAPPER

        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL : repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON : getRoleRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL : roleRepository
        deactivate REPOS_SINGLETON

        CTRL -> ROLE_REPO : getRoles()
        activate ROLE_REPO
            ROLE_REPO --> CTRL : roleList
        deactivate ROLE_REPO

        CTRL -> ROLE_MAPPER : toDTOList(roleList)
        activate ROLE_MAPPER
            ROLE_MAPPER --> CTRL : roleDTOList
        deactivate ROLE_MAPPER

    end
    autonumber 4
    <-- CTRL : politicalAgentDTOList, roleDTOList
deactivate CTRL

@enduml
