@startuml
title US04 - Register an Institution
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class Administrator {
}

class Institution {
    name
    taxId
}

enum InstitutionType << Enum >> {
    COMPANY
    POLITICAL_PARTY
    FOUNDATION
    INSTITUTE
    ASSOCIATION
}

Administrator "1" -- "0..*" Institution : registers
Institution --> "1" InstitutionType

@enduml