@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ApproveRejectRegistrationController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "registrationRequestRepository\n:RegistrationRequestRepository" as REQ_REPO
participant "mapper\n:RegistrationRequestMapper" as MAPPER

autonumber
-> CTRL : getPendingRegistrationRequests()
activate CTRL
    CTRL -> REPOS : getInstance()
    activate REPOS
        REPOS --> CTRL : repositories
    deactivate REPOS

    CTRL -> REPOS_SINGLETON : getRegistrationRequestRepository()
    activate REPOS_SINGLETON
        REPOS_SINGLETON --> CTRL : registrationRequestRepository
    deactivate REPOS_SINGLETON

    CTRL -> REQ_REPO : getPendingRegistrationRequests()
    activate REQ_REPO
        REQ_REPO --> CTRL : pendingRequests
    deactivate REQ_REPO

    CTRL -> MAPPER : toPendingDTOList(pendingRequests)
    activate MAPPER
        MAPPER --> CTRL : pendingRequestDTOList
    deactivate MAPPER

    <-- CTRL : pendingRequestDTOList
deactivate CTRL

@enduml
