@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ApproveRejectRegistrationController" as CTRL
participant "registrationRequest\n:RegistrationRequest" as REQ
participant "annotation\n:Annotation" as ANNOTATION

autonumber 15
-> CTRL : rejectRegistrationRequest(rejectionReason)

autonumber 15.1
activate CTRL

    group Reject Registration Request

        note right of CTRL
            administrator was obtained
            through the Get Administrator partial SD
        end note

        CTRL -> REQ : reject(administrator, rejectionReason)
        activate REQ

            REQ -> REQ : registerDecision(administrator)
            activate REQ
                REQ --> REQ : decision recorded
            deactivate REQ

            REQ --> ANNOTATION** : create(rejectionReason)

            REQ --> CTRL : annotation
        deactivate REQ

    end

    autonumber 16
    <-- CTRL : annotation

deactivate CTRL

@enduml