@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ApproveRejectRegistrationController" as CTRL
participant "registrationRequest\n:RegistrationRequest" as REQ
participant "mapper\n:RegistrationRequestMapper" as MAPPER

autonumber
-> CTRL : rejectRegistrationRequest(decisionDTO)
activate CTRL
    note right of CTRL
        administrator was obtained through
        the Get Administrator partial SD
    end note

    CTRL -> REQ : reject(administrator, decisionDTO.rejectionReason)
    activate REQ
        REQ --> CTRL : annotation
    deactivate REQ

    CTRL -> MAPPER : toDetailsDTO(registrationRequest)
    activate MAPPER
        MAPPER --> CTRL : updatedRequestDetailsDTO
    deactivate MAPPER

    <-- CTRL : updatedRequestDetailsDTO
deactivate CTRL

@enduml
