@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Political\nAgent" as PoliticalAgent
participant ":System" as System

activate PoliticalAgent

PoliticalAgent -> System : asks to submit a declaration
activate System

System --> PoliticalAgent : requests declaration type
deactivate System

PoliticalAgent -> System : selects declaration type
activate System

System --> PoliticalAgent : requests positions data
deactivate System

loop for each position
    PoliticalAgent -> System : enters position data
    activate System
    System --> PoliticalAgent : validates position
    deactivate System
end

System --> PoliticalAgent : requests subsidies data

loop for each subsidy
    PoliticalAgent -> System : enters subsidy data
    activate System
    System --> PoliticalAgent : validates subsidy
    deactivate System
end

System --> PoliticalAgent : requests assets data

loop for each asset
    PoliticalAgent -> System : enters asset data
    activate System
    System --> PoliticalAgent : validates asset
    deactivate System
end

System --> PoliticalAgent : requests participations data

loop for each participation
    PoliticalAgent -> System : enters participation data
    activate System
    System --> PoliticalAgent : validates participation
    deactivate System
end

System --> PoliticalAgent : shows all data and requests confirmation

PoliticalAgent -> System : confirms declaration
activate System

System --> PoliticalAgent : displays operation success
deactivate System

@enduml