@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

abstract class Person {
    name
    taxId
    email
    password
}

class Citizen {
}

class Journalist {
    pressCardNumber
}

class PoliticalAgent {
}

class Declaration {
    submissionDate
    declarantName
}

abstract class Section {
}

class AssetSection {
}

abstract class Field {
}

class AssetField {
}

class Property {
    acquisitionValue
    marketValue
}

enum PropertyType {
    URBAN
    RURAL
}

class Location {
    parish
    municipality
    district
}

Person <|-- Citizen
Person <|-- Journalist
Person <|-- PoliticalAgent

Section <|-- AssetSection
Field <|-- AssetField

PoliticalAgent "1" -- "0..*" Declaration : submits >
Declaration *-- "4" Section
AssetSection *-- "*" AssetField
AssetField *-- "1" Property
Property --> "1" PropertyType
Property "1" -- "1" Location : located in >

Citizen "1" -- "0..*" Declaration : consults >
Journalist "1" -- "0..*" Declaration : consults >

note right of Citizen
Displayed asset data is filtered
according to role visibility rules.
end note

@enduml