@startuml
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Political Agent" as AGENT

participant ":ListInstitutionUI" as UI
participant ":ListInstitutionController" as CTRL

participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "institutionTypeRepository\n:InstitutionTypeRepository" as TYPE_REPO
participant "institutionRepository\n:InstitutionRepository" as INST_REPO

activate AGENT

AGENT -> UI : asks to list institutions
activate UI

    UI -> CTRL** : create()

    UI -> CTRL : getInstitutionTypes()
    activate CTRL

        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL : repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON : getInstitutionTypeRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL : institutionTypeRepository
        deactivate REPOS_SINGLETON

        CTRL -> TYPE_REPO : getInstitutionTypes()
        activate TYPE_REPO
            TYPE_REPO --> CTRL : institutionTypeList
        deactivate TYPE_REPO

        CTRL --> UI : institutionTypeList
    deactivate CTRL

    UI --> AGENT : displays Institution types

    AGENT -> UI : selects type
    activate UI

        UI -> CTRL : getInstitutionsByType(type)
        activate CTRL

            CTRL -> REPOS : getInstance()
            activate REPOS
                REPOS --> CTRL : repositories
            deactivate REPOS

            CTRL -> REPOS_SINGLETON : getInstitutionRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL : institutionRepository
            deactivate REPOS_SINGLETON

            CTRL -> INST_REPO : getInstitutionsByType(type)
            activate INST_REPO
                INST_REPO --> CTRL : institutionList
            deactivate INST_REPO

            CTRL -> INST_REPO : getInstitutionsSorted()
            activate INST_REPO
                INST_REPO --> CTRL : sortedInstitutionList
            deactivate INST_REPO

            CTRL --> UI : institutionList
        deactivate CTRL

    UI --> AGENT : displays institutions ordered alphabetically

deactivate UI
deactivate AGENT

@enduml
