@startuml
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Political Agent" as AGENT
participant ":ListInstitutionsUI" as UI
participant ":ListInstitutionsController" as CTRL

activate AGENT

AGENT -> UI : asks to list institutions
activate UI

    UI -> CTRL** : create()

    UI -> CTRL : getListInstitutions()
    activate CTRL
        CTRL --> UI : institutionList
    deactivate CTRL

    UI --> AGENT : displays institutions grouped by type and sorted alphabetically

deactivate UI
deactivate AGENT

ref over CTRL : Get Institutions List
    participant ":ListInstitutionsController" as CTRL
    participant "Repositories" as REPOS
    participant "repositories\n:Repositories" as REPOS_SINGLETON
    participant "institutionRepository\n:InstitutionRepository" as INST_REPO
    
    activate CTRL
        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL : repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON : getInstitutionRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL : institutionRepository
        deactivate REPOS_SINGLETON

        CTRL -> INST_REPO : getInstitutionsGroupedByType()
        activate INST_REPO
            INST_REPO --> CTRL : institutionList
        deactivate INST_REPO

        CTRL -> INST_REPO : getInstitutionsSorted()
        activate INST_REPO
            INST_REPO --> CTRL : sortedInstitutionList
        deactivate INST_REPO

        CTRL --> CTRL : return institutionList
    deactivate CTRL
end ref

@enduml
