@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Administrator" as Admin
participant ":System" as System

activate Admin

    Admin -> System : asks to manage pending registration requests
    activate System
        System --> Admin : presents list of pending registration requests
    deactivate System

    Admin -> System : selects a registration request
    activate System
        System --> Admin : shows registration request details
    deactivate System

    Admin -> System : accepts or rejects the registration request
    activate System
        System --> Admin : asks for confirmation
    deactivate System

    Admin -> System : confirms decision
    activate System
        System --> Admin : informs that the operation was carried out successfully
    deactivate System

deactivate Admin
@enduml