@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Administrator" as Admin
participant ":System" as System

activate Admin

    Admin -> System : asks to review registration requests
    activate System

        System --> Admin : shows pending registration requests
    deactivate System

    Admin -> System : selects a registration request
    activate System

        System --> Admin : shows request details
    deactivate System

    Admin -> System : accepts/rejects the registration request
    activate System

        System --> Admin : asks for confirmation
    deactivate System

    Admin -> System : confirms decision
    activate System

        System --> Admin : displays operation success
    deactivate System

deactivate Admin

@enduml