@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":RequestRegistrationUI" as UI
participant ":RequestRegistrationController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "institutionRepository\n:InstitutionRepository" as INST_REPO
participant "requestRegistrationMapper\n:RequestRegistrationMapper" as MAPPER

UI -> CTRL : getInstitutions()
activate CTRL
    CTRL -> REPOS : getInstance()
    activate REPOS
        REPOS --> CTRL : repositories
    deactivate REPOS

    CTRL -> REPOS_SINGLETON : getInstitutionRepository()
    activate REPOS_SINGLETON
        REPOS_SINGLETON --> CTRL : institutionRepository
    deactivate REPOS_SINGLETON

    CTRL -> INST_REPO : getInstitutions()
    activate INST_REPO
        INST_REPO --> CTRL : institutions
    deactivate INST_REPO

    CTRL -> MAPPER : toInstitutionDTOList(institutions)
    activate MAPPER
        MAPPER --> CTRL : institutionDTOList
    deactivate MAPPER

    CTRL --> UI : institutionDTOList
deactivate CTRL

@enduml
