@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class User {
    name
    email
    password
}

class Administrator {
    name
    email
    password
}

class Role {
    designation
}

class RegistrationRequest {
    requestDate
    status
}

User "1" -- "0..1" RegistrationRequest : requests >
Administrator "1" -- "0..*" RegistrationRequest : reviews >
RegistrationRequest "1" -- "1" Role : refers to >
User "0..*" -- "0..1" Role : is assigned to >

@enduml