@startuml
title US02 - Approve/Reject Registration
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

skinparam class {
    BackgroundColor<<Abstract>> White
    BackgroundColor<<Enum>> White
}

enum RequestedRole << Enum >> {
  POLITICAL_AGENT
  CITIZEN
  JOURNALIST
  ETHICS_COMMITTEE_MEMBER
}

enum RequestStatus << Enum >> {
  PENDING
  ACCEPTED
  REJECTED
}

abstract class User << Abstract >> {
    name
    taxId
    email
    password
}

class PoliticalAgent {}
class Citizen {}
class Journalist {
    pressCardNumber
}
class EthicsCommitteeMember {}

class Administrator {}

class RegistrationRequest {
    requestDate
}

User <|-- PoliticalAgent
User <|-- Citizen
User <|-- Journalist
User <|-- EthicsCommitteeMember
User <|-- Administrator

User "1" -- "0..*" RegistrationRequest : requests >
Administrator "1" -- "0..*" RegistrationRequest : reviews >
RegistrationRequest --> "1" RequestStatus
RegistrationRequest "1" -- "1" RequestedRole : refers to >

@enduml