@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class Administrator {
    name
    email
    password
}

class RegistrationRequest {
    requestDate
    status
}

class Role {
    designation
}

Administrator "1" -- "0..*" RegistrationRequest : reviews >
RegistrationRequest "1" -- "1" Role : refers to >

@enduml