@startuml
title US02 - Approve/Reject Registration
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Administrator" as Admin
participant ":System" as System

activate Admin

    Admin -> System : asks to manage pending registration requests
    activate System
        System --> Admin : presents list of pending registration requests
    deactivate System

    Admin -> System : selects a registration request
    activate System
        System --> Admin : shows registration request details
    deactivate System

    alt accepts registration request

        Admin -> System : accepts the registration request
        activate System
            System --> Admin : asks for confirmation
        deactivate System

        Admin -> System : confirms acceptance
        activate System
            System --> Admin : informs that the request was accepted and the user account was created
        deactivate System

    else rejects registration request

        Admin -> System : rejects the registration request
        activate System
            System --> Admin : asks for rejection reason
        deactivate System

        Admin -> System : provides rejection reason
        activate System
            System --> Admin : asks for confirmation
        deactivate System

        Admin -> System : confirms rejection
        activate System
            System --> Admin : informs that the request was rejected
        deactivate System

    end

deactivate Admin
@enduml