@startuml
top to bottom direction
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class PoliticalAgent {
    name
    email
}

class Declaration {
    submissionDate
    type
}

class Position {
    type
    function
    remuneration
}

class Subsidy {
    amount
}

class Asset {
    type
    estimatedValue
}

class Participation {
    type
    marketValue
}

class Institution {
    name
}

PoliticalAgent "1" -down- "0..*" Declaration : submits

Declaration "1" -down- "0..*" Position : includes
Declaration "1" -down- "0..*" Subsidy : includes
Declaration "1" -down- "0..*" Asset : includes
Declaration "1" -down- "0..*" Participation : includes

Position "0..*" -down- "1" Institution : held at
Subsidy "0..*" -down- "1" Institution : received from
Participation "0..*" -down- "1" Institution : held in

@enduml